# Generated by Django 3.0.6 on 2020-05-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='autor',
            new_name='author',
        ),
    ]
